# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install --only=dev
  displayName: 'npm install'
  

- script: |
    npm i -D @playwright/test
  displayName: 'playwright install'

- script: |
    npx playwright install
  displayName: 'browsers available install'

- script: |
    npx playwright test tests/demo
  displayName: 'test run demo'